Fixes stepper styles
hackforla/calendaring-service-fe pull request #14
Opened 2021-02-21 00:50 UTC by jonathanbutler7

2021-02-21 01:59 UTC, javaprincess approved these changes

2021-02-21 02:02 UTC, javaprincess requested changes

2021-02-21 02:02 UTC, javaprincess commented on app/src/components/MeetingTypes/MeetingTypeStyles.js
> +const useStyles = makeStyles({
Can we put this stylings in a .css file and then import the .css file?

2021-02-23 21:07 UTC, jonathanbutler7 commented
Made requested changes and also added Typography styles to theme and changed out all <h1>, <h2>, etc. tags for Typography.

2021-02-28 02:11 UTC, merged