CS-31
hackforla/calendaring-service-fe pull request #30
Opened 2021-05-22 19:10 UTC by PaulSoonMinChoi

# **This Pr:** 

- Creates `CalendarSelectedTimes.js`, `SelectTimeRange.js`, `SelectTimeRangeStyles.js`, `MuiMenuItem.js`
- Updates `Header.js` to include time slots validation. 
- Adds `./calendarselectedtimes` route to `app.js`
- Adds `ProgressButtons.js` in the shared folder to be reusable in other components. 

## **Notes:** 
Checkmark functionality is still not fully functioning with the rest of the MaterialUI components. So I have left some comments in hopes of figuring out the issue! 

## Screenshots: 

### Default Page
<img width="375" alt="Screen Shot 2021-05-22 at 12 01 17 PM" src="https://user-images.githubusercontent.com/65373185/119238126-879e8980-baf5-11eb-8ae2-7c4537882157.png">

### Two times selected from one day. 
<img width="374" alt="Screen Shot 2021-05-22 at 12 01 50 PM" src="https://user-images.githubusercontent.com/65373185/119238180-d9471400-baf5-11eb-90b8-58a6cb4e917c.png">

### Times selected from all available days. 
<img width="375" alt="Screen Shot 2021-05-22 at 12 01 34 PM" src="https://user-images.githubusercontent.com/65373185/119238213-08f61c00-baf6-11eb-9dad-58726cbedbde.png">

### Shows Checkmark functionality but conflicts with other Elements within the component.
<img width="375" alt="Screen Shot 2021-05-22 at 12 08 25 PM" src="https://user-images.githubusercontent.com/65373185/119238285-7e61ec80-baf6-11eb-9568-9a3bd5af4c3d.png">

2021-05-23 02:01 UTC, jonathanbutler7 requested changes
Looking really good! Just a few small changes

2021-05-23 02:01 UTC, jonathanbutler7 commented on src/components/Scheduling/SelectTimeRange.js
> +              value={time}
Would you mind just adding `onKeyDown={keyDownHandler}` here? 

Something like:
```jsx
const keyDownHandler = (e) => {
  if (e.key === ' ' || e.key === 'Enter') {
    // call your handleChange function
  }
```

2021-05-25 17:09 UTC, PaulSoonMinChoi commented on src/components/Scheduling/CalendarSelectedTimes.js
> +  const [allSelectedTimes, setAllSelectedTimes] = useState({
Which line from 25-28 are you referring to? Or are you talking about all of them?

2021-05-25 17:11 UTC, PaulSoonMinChoi commented on src/components/Scheduling/Header.js
> +          You have chosen {`${slots}`} of {`${maxSlots}`} time slots
In the Figma mock-up, they have it set up like how I wrote but I can change it if it's not an issue!

2021-05-25 17:55 UTC, PaulSoonMinChoi commented on src/components/Scheduling/Header.js
> +          {`${action} (${maxSlots} total)`}
This line as well, I copied from the Figma mock-ups! If it's okay to change it I'm totally for it too.

2021-05-25 17:59 UTC, jonathanbutler7 commented on src/components/Scheduling/Header.js
> +          You have chosen {`${slots}`} of {`${maxSlots}`} time slots
I just mean your usage of brackets/jsx. The change I proposed renders the same text to the page.

2021-05-25 18:00 UTC, jonathanbutler7 commented on src/components/Scheduling/CalendarSelectedTimes.js
> +  const [allSelectedTimes, setAllSelectedTimes] = useState({
I'm referring to how you initialize state in line 28.

2021-05-25 18:40 UTC, PaulSoonMinChoi commented on src/components/Scheduling/Header.js
> +          You have chosen {`${slots}`} of {`${maxSlots}`} time slots
Oh, I see the issue! Thanks will get that fixed.

2021-05-25 19:08 UTC, PaulSoonMinChoi commented on src/components/Scheduling/CalendarSelectedTimes.js
> +  const [allSelectedTimes, setAllSelectedTimes] = useState({
So I actually removed the initial state since I will begin populating it when someone selects a date. Thanks for catching that as well!

2021-05-26 01:01 UTC, jonathanbutler7 approved these changes
Great job

2021-05-26 01:01 UTC, merged