CS-32
hackforla/calendaring-service-fe pull request #32
Opened 2021-05-29 03:03 UTC by kceddinger

Implements caseworker flow with available components

2021-05-29 17:00 UTC, jonathanbutler7 requested changes
Kimberly this looks awesome! I just left you a couple thoughts.

My bad for giving bad instructions in the Jira ticket on how to implement <Link>. That was how I had always done it before, but I hadn't considered this specific use case that all the buttons in the mockups are actually links to other pages. Hopefully I'm making sense, let me know if I'm being confusing lol. I left you an example and a link to the materialUI docs of how to use their buttons with react-router's api. It's pretty cool that they got that integration so seamless IMO. 

Please let me know if you have any questions or further thoughts!

2021-06-01 00:33 UTC, kceddinger commented on src/components/Welcome/DashboardBody.js
> +        <Link to="/scheduledays">
Awesome! I was curious about the link's effect on the button. I'll try this out.

2021-06-01 00:37 UTC, kceddinger commented on src/components/Welcome/DashboardBody.js
> +      <Switch>
Early into my implementation I thought each use of the router needed a switch statement. I thought I had removed all of these - nice catch, I'll get rid of it!

2021-06-01 00:40 UTC, kceddinger commented on src/App.js
> +    <Router>
Oh I didn't realize that, thank you! Removing.

2021-06-01 00:44 UTC, kceddinger commented on src/components/Success/SuccessScreenTwo.js
> +    <Switch>
I was mistaken and didn't completely eliminate the switch/route statements from other components. My bad!

2021-06-01 02:45 UTC, jonathanbutler7 approved these changes
Looks great

2021-06-01 02:45 UTC, merged